id=$(docker ps --format="{{.ID}}" --filter "name=logiciel_back-end") 
test1="test_setpts.js"
test2="test_get_tentative.js"
test3="test_subscribe.js"
test4="test_processdata.js"
test5="test_noteTotaleModule.js"
path="./tests/"
docker exec "$id" node "$path$test1" > "$test1.res"
echo "Les resultats du tests $test1 sont disponibles dans le fichier : $test1.res"
docker exec "$id" node "$path$test2" > "$test2.res"
echo "Les resultats du tests $test2 sont disponibles dans le fichier : $test2.res"
docker exec "$id" node "$path$test3" > "$test3.res"
echo "Les resultats du tests $test3 sont disponibles dans le fichier : $test3.res"
docker exec "$id" node "$path$test4" > "$test4.res"
echo "Les resultats du tests $test4 sont disponibles dans le fichier : $test4.res"
docker exec "$id" node "$path$test5" > "$test5.res"
echo "Les resultats du tests $test5 sont disponibles dans le fichier : $test5.res"