### STAGE 1: Build ###
FROM node:10.20.1-alpine3.11
WORKDIR /app

# install and cache app dependencies
COPY package.json /app/package.json
RUN npm install
RUN npm install -g @angular/cli
COPY . .

EXPOSE 4200

CMD ["ng","serve","--host", "0.0.0.0"]